/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Vector;
import javax.swing.DefaultListModel;

/**
 *
 * @author Agustin
 */
public class Biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form Biblioteca
     */
    public Biblioteca() {
        initComponents();
    }
//    Creamos un vector de libros
    Vector<Libro> Libros = new Vector<Libro>();
    int contador = 0000;
    int objeto;
    DefaultListModel lista1 = new DefaultListModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        cboxBuscarpor = new javax.swing.JComboBox();
        lblBuscarpor = new javax.swing.JLabel();
        txtPrestamonuevo = new javax.swing.JTextField();
        txtFechanuevo = new javax.swing.JTextField();
        lblPrestamo = new javax.swing.JLabel();
        lblFechaprestamo = new javax.swing.JLabel();
        btnNuevoprestamo = new javax.swing.JButton();
        lblPrestamoNuevo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblFoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTitulo2 = new javax.swing.JTextField();
        txtAutor2 = new javax.swing.JTextField();
        txtEditorial2 = new javax.swing.JTextField();
        txtAño2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTipodelibro2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book For (Búsqueda de Libros)");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cboxBuscarpor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TITULO", "AUTOR", "EDITORIAL", "TIPO DE LIBRO", "AÑO", "NUMERO" }));
        cboxBuscarpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxBuscarporActionPerformed(evt);
            }
        });

        lblBuscarpor.setText("Buscar por:");

        txtFechanuevo.setText("DD/MM/AA");
        txtFechanuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechanuevoActionPerformed(evt);
            }
        });

        lblPrestamo.setText("Nombre:");

        lblFechaprestamo.setText("Fecha:");

        btnNuevoprestamo.setText("Agregar");
        btnNuevoprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoprestamoActionPerformed(evt);
            }
        });

        lblPrestamoNuevo.setText("NUEVO PRESTAMO:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Título", "Autor", "Editorial", "Tipo de libro", "Año", "Nombre", "Fecha", "D.N.I"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblDNI.setText("D.N.I:");

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/g6398_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBuscarpor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxBuscarpor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblPrestamoNuevo))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblPrestamo)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPrestamonuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblFechaprestamo)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFechanuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnNuevoprestamo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDNI)
                                .addGap(29, 29, 29)
                                .addComponent(txtDNI)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFoto)))
                .addContainerGap(275, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(jSeparator2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboxBuscarpor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBuscarpor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblPrestamoNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrestamo)
                            .addComponent(txtPrestamonuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaprestamo)
                            .addComponent(txtFechanuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDNI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevoprestamo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Busqueda", jPanel1);

        jLabel6.setText("TITULO");

        jLabel7.setText("AUTOR");

        jLabel8.setText("EDITORIAL");

        jLabel9.setText("AÑO");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel11.setText("TIPO DE LIBRO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitulo2)
                            .addComponent(txtAutor2)
                            .addComponent(txtEditorial2)
                            .addComponent(txtAño2)
                            .addComponent(txtTipodelibro2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(9, 9, 9)))
                .addContainerGap(515, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAutor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEditorial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAño2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtTipodelibro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar libro", jPanel2);

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Libros", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
//        Creamos un libro y lo agregamos al vector 
//        Despues "setteo" como valor nulo a las casillas de texto en el grafico del programa

        contador = 1 + contador;
        Libro libro = new Libro(txtTitulo2.getText(), txtAutor2.getText(), txtEditorial2.getText(), txtAño2.getText(), txtTipodelibro2.getText(), "" + contador);
        Libros.addElement(libro);
        txtTitulo2.setText(null);
        txtAutor2.setText(null);
        txtAño2.setText(null);
        txtEditorial2.setText(null);
        txtTipodelibro2.setText(null);
        lista1.addElement(libro.getTitulo());
        jList1.setModel(lista1);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void btnNuevoprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoprestamoActionPerformed
        //        Cuando ya busqué un libro con el programa, luego voy a poder agregar un prestamo, y con este codigo se realiza eso
        Libros.elementAt(objeto).setUltimoprestamo(txtPrestamonuevo.getText());
        Libros.elementAt(objeto).setFechaultimoprestamo(txtFechanuevo.getText());
        Libros.elementAt(objeto).setDNI(txtDNI.getText());
    }//GEN-LAST:event_btnNuevoprestamoActionPerformed

    private void txtFechanuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechanuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechanuevoActionPerformed

    private void cboxBuscarporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxBuscarporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxBuscarporActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //
        int x = 0, y = 0;
        for (int i = 0; i < 100; i++) {
            if (cboxBuscarpor.getSelectedIndex() == 0) {
                if (Libros.elementAt(i).getTitulo().equals(txtBuscar.getText())) {
                    objeto = i;
                    if (jTable1.getValueAt(x, y) == null) {
                        x++;
                        for (int j = 0; j < 9; j++) {
                            if (j == 0) {
                                jTable1.setValueAt(Libros.elementAt(i).getNumero(), x, j);
                            } else if (j == 1) {
                                jTable1.setValueAt(Libros.elementAt(i).getTitulo(), x, j);
                            } else if (j == 2) {
                                jTable1.setValueAt(Libros.elementAt(i).getAutor(), x, j);
                            } else if (j == 3) {
                                jTable1.setValueAt(Libros.elementAt(i).getEditorial(), x, j);
                            } else if (j == 4) {
                                jTable1.setValueAt(Libros.elementAt(i).getTipo(), x, j);
                            } else if (j == 5) {
                                jTable1.setValueAt(Libros.elementAt(i).getAño(), x, j);
                            } else if (j == 6) {
                                jTable1.setValueAt(Libros.elementAt(i).getUltimoprestamo(), x, j);
                            } else if (j == 7) {
                                jTable1.setValueAt(Libros.elementAt(i).getFechaultimoprestamo(), x, j);
                            } else if (j == 8) {
                                jTable1.setValueAt(Libros.elementAt(i).getDNI(), x, j);
                            }
                        }
                    }
                }
            } else if (cboxBuscarpor.getSelectedIndex() == 1) {
                if (Libros.elementAt(i).getAutor().equals(txtBuscar.getText())) {
                    objeto = i;
                    if (jTable1.getValueAt(x, y) == null) {
                        x++;
                        for (int j = 0; j < 9; j++) {
                            if (j == 0) {
                                jTable1.setValueAt(Libros.elementAt(i).getNumero(), x, j);
                            } else if (j == 1) {
                                jTable1.setValueAt(Libros.elementAt(i).getTitulo(), x, j);
                            } else if (j == 2) {
                                jTable1.setValueAt(Libros.elementAt(i).getAutor(), x, j);
                            } else if (j == 3) {
                                jTable1.setValueAt(Libros.elementAt(i).getEditorial(), x, j);
                            } else if (j == 4) {
                                jTable1.setValueAt(Libros.elementAt(i).getTipo(), x, j);
                            } else if (j == 5) {
                                jTable1.setValueAt(Libros.elementAt(i).getAño(), x, j);
                            } else if (j == 6) {
                                jTable1.setValueAt(Libros.elementAt(i).getUltimoprestamo(), x, j);
                            } else if (j == 7) {
                                jTable1.setValueAt(Libros.elementAt(i).getFechaultimoprestamo(), x, j);
                            } else if (j == 8) {
                                jTable1.setValueAt(Libros.elementAt(i).getDNI(), x, j);
                            }
                        }
                    }
                }
            } else if (cboxBuscarpor.getSelectedIndex() == 2) {
                if (Libros.elementAt(i).getEditorial().equals(txtBuscar.getText())) {
                    objeto = i;
                    objeto = Integer.parseInt(Libros.elementAt(i).getNumero());
                    if (jTable1.getValueAt(x, y) == null) {
                        x++;
                        for (int j = 0; j < 9; j++) {
                            if (j == 0) {
                                jTable1.setValueAt(Libros.elementAt(i).getNumero(), x, j);
                            } else if (j == 1) {
                                jTable1.setValueAt(Libros.elementAt(i).getTitulo(), x, j);
                            } else if (j == 2) {
                                jTable1.setValueAt(Libros.elementAt(i).getAutor(), x, j);
                            } else if (j == 3) {
                                jTable1.setValueAt(Libros.elementAt(i).getEditorial(), x, j);
                            } else if (j == 4) {
                                jTable1.setValueAt(Libros.elementAt(i).getTipo(), x, j);
                            } else if (j == 5) {
                                jTable1.setValueAt(Libros.elementAt(i).getAño(), x, j);
                            } else if (j == 6) {
                                jTable1.setValueAt(Libros.elementAt(i).getUltimoprestamo(), x, j);
                            } else if (j == 7) {
                                jTable1.setValueAt(Libros.elementAt(i).getFechaultimoprestamo(), x, j);
                            } else if (j == 8) {
                                jTable1.setValueAt(Libros.elementAt(i).getDNI(), x, j);
                            }
                        }
                    }
                }
            } else if (cboxBuscarpor.getSelectedIndex() == 3) {
                if (Libros.elementAt(i).getTipo().equals(txtBuscar.getText())) {
                    objeto = i;
                    if (jTable1.getValueAt(x, y) == null) {
                        x++;
                        for (int j = 0; j < 9; j++) {
                            if (j == 0) {
                                jTable1.setValueAt(Libros.elementAt(i).getNumero(), x, j);
                            } else if (j == 1) {
                                jTable1.setValueAt(Libros.elementAt(i).getTitulo(), x, j);
                            } else if (j == 2) {
                                jTable1.setValueAt(Libros.elementAt(i).getAutor(), x, j);
                            } else if (j == 3) {
                                jTable1.setValueAt(Libros.elementAt(i).getEditorial(), x, j);
                            } else if (j == 4) {
                                jTable1.setValueAt(Libros.elementAt(i).getTipo(), x, j);
                            } else if (j == 5) {
                                jTable1.setValueAt(Libros.elementAt(i).getAño(), x, j);
                            } else if (j == 6) {
                                jTable1.setValueAt(Libros.elementAt(i).getUltimoprestamo(), x, j);
                            } else if (j == 7) {
                                jTable1.setValueAt(Libros.elementAt(i).getFechaultimoprestamo(), x, j);
                            } else if (j == 8) {
                                jTable1.setValueAt(Libros.elementAt(i).getDNI(), x, j);
                            }

                        }
                    }
                }
            } else if (cboxBuscarpor.getSelectedIndex() == 4) {
                if (Libros.elementAt(i).getAño().equals(txtBuscar.getText())) {
                    objeto = i;
                    if (jTable1.getValueAt(x, y) == null) {
                        x++;
                        for (int j = 0; j < 9; j++) {
                            if (j == 0) {
                                jTable1.setValueAt(Libros.elementAt(i).getNumero(), x, j);
                            } else if (j == 1) {
                                jTable1.setValueAt(Libros.elementAt(i).getTitulo(), x, j);
                            } else if (j == 2) {
                                jTable1.setValueAt(Libros.elementAt(i).getAutor(), x, j);
                            } else if (j == 3) {
                                jTable1.setValueAt(Libros.elementAt(i).getEditorial(), x, j);
                            } else if (j == 4) {
                                jTable1.setValueAt(Libros.elementAt(i).getTipo(), x, j);
                            } else if (j == 5) {
                                jTable1.setValueAt(Libros.elementAt(i).getAño(), x, j);
                            } else if (j == 6) {
                                jTable1.setValueAt(Libros.elementAt(i).getUltimoprestamo(), x, j);
                            } else if (j == 7) {
                                jTable1.setValueAt(Libros.elementAt(i).getFechaultimoprestamo(), x, j);
                            } else if (j == 8) {
                                jTable1.setValueAt(Libros.elementAt(i).getDNI(), x, j);
                            }
                        }
                    }
                }
            } else if (cboxBuscarpor.getSelectedIndex() == 5) {
                if (Libros.elementAt(i).getNumero().equals(txtBuscar.getText())) {
                    objeto = i;
                    if (jTable1.getValueAt(x, y) == null) {
                        x++;
                        for (int j = 0; j < 9; j++) {
                            if (j == 0) {
                                jTable1.setValueAt(Libros.elementAt(i).getNumero(), x, j);
                            } else if (j == 1) {
                                jTable1.setValueAt(Libros.elementAt(i).getTitulo(), x, j);
                            } else if (j == 2) {
                                jTable1.setValueAt(Libros.elementAt(i).getAutor(), x, j);
                            } else if (j == 3) {
                                jTable1.setValueAt(Libros.elementAt(i).getEditorial(), x, j);
                            } else if (j == 4) {
                                jTable1.setValueAt(Libros.elementAt(i).getTipo(), x, j);
                            } else if (j == 5) {
                                jTable1.setValueAt(Libros.elementAt(i).getAño(), x, j);
                            } else if (j == 6) {
                                jTable1.setValueAt(Libros.elementAt(i).getUltimoprestamo(), x, j);
                            } else if (j == 7) {
                                jTable1.setValueAt(Libros.elementAt(i).getFechaultimoprestamo(), x, j);
                            } else if (j == 8) {
                                jTable1.setValueAt(Libros.elementAt(i).getDNI(), x, j);
                            }
                        }
                    }

                }
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevoprestamo;
    private javax.swing.JComboBox cboxBuscarpor;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBuscarpor;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblFechaprestamo;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JLabel lblPrestamoNuevo;
    private javax.swing.JTextField txtAutor2;
    private javax.swing.JTextField txtAño2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEditorial2;
    private javax.swing.JTextField txtFechanuevo;
    private javax.swing.JTextField txtPrestamonuevo;
    private javax.swing.JTextField txtTipodelibro2;
    private javax.swing.JTextField txtTitulo2;
    // End of variables declaration//GEN-END:variables
}
